config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :mentors
  resources :enrollments
  resources :mentor_enrollment_assignments
  resources :lessons
  resources :courses
  resources :coding_classes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/mentor_enrollment_assignment.rb
class MentorEnrollmentAssignment < ApplicationRecord
  belongs_to :mentor
  belongs_to :enrollment
  validates :enrollment, uniqueness: true
end

app/controllers/mentor_enrollment_assignments_controller.rb
class MentorEnrollmentAssignmentsController < ApplicationController
  before_action :set_mentor_enrollment_assignment, only: %i[ show edit update destroy ]

  # GET /mentor_enrollment_assignments or /mentor_enrollment_assignments.json
  def index
    @mentor_enrollment_assignments = MentorEnrollmentAssignment.all
  end

  # GET /mentor_enrollment_assignments/1 or /mentor_enrollment_assignments/1.json
  def show
  end

  # GET /mentor_enrollment_assignments/new
  def new
    @mentor_enrollment_assignment = MentorEnrollmentAssignment.new
  end

  # GET /mentor_enrollment_assignments/1/edit
  def edit
  end

  # POST /mentor_enrollment_assignments or /mentor_enrollment_assignments.json
  def create
    @mentor_enrollment_assignment = MentorEnrollmentAssignment.new(mentor_enrollment_assignment_params)

    respond_to do |format|
      if @mentor_enrollment_assignment.save
        format.html { redirect_to @mentor_enrollment_assignment, notice: "Mentor enrollment assignment was successfully created." }
        format.json { render :show, status: :created, location: @mentor_enrollment_assignment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mentor_enrollment_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mentor_enrollment_assignments/1 or /mentor_enrollment_assignments/1.json
  def update
    respond_to do |format|
      if @mentor_enrollment_assignment.update(mentor_enrollment_assignment_params)
        format.html { redirect_to @mentor_enrollment_assignment, notice: "Mentor enrollment assignment was successfully updated." }
        format.json { render :show, status: :ok, location: @mentor_enrollment_assignment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mentor_enrollment_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentor_enrollment_assignments/1 or /mentor_enrollment_assignments/1.json
  def destroy
    @mentor_enrollment_assignment.destroy!

    respond_to do |format|
      format.html { redirect_to mentor_enrollment_assignments_path, status: :see_other, notice: "Mentor enrollment assignment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mentor_enrollment_assignment
      @mentor_enrollment_assignment = MentorEnrollmentAssignment.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def mentor_enrollment_assignment_params
      params.expect(mentor_enrollment_assignment: [ :mentor_id, :enrollment_id ])
    end
end

app/views/mentor_enrollment_assignments/_form.html.erb
<%= form_with(model: mentor_enrollment_assignment) do |form| %>
  <% if mentor_enrollment_assignment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mentor_enrollment_assignment.errors.count, "error") %> prohibited this mentor_enrollment_assignment from being saved:</h2>

      <ul>
        <% mentor_enrollment_assignment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :mentor_id, style: "display: block" %>
    <%= form.text_field :mentor_id %>
  </div>

  <div>
    <%= form.label :enrollment_id, style: "display: block" %>
    <%= form.text_field :enrollment_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mentor_enrollment_assignments/_mentor_enrollment_assignment.html.erb
<div id="<%= dom_id mentor_enrollment_assignment %>">
  <p>
    <strong>Mentor:</strong>
    <%= mentor_enrollment_assignment.mentor_id %>
  </p>

  <p>
    <strong>Enrollment:</strong>
    <%= mentor_enrollment_assignment.enrollment_id %>
  </p>

</div>

app/views/mentor_enrollment_assignments/edit.html.erb
<% content_for :title, "Editing mentor enrollment assignment" %>

<h1>Editing mentor enrollment assignment</h1>

<%= render "form", mentor_enrollment_assignment: @mentor_enrollment_assignment %>

<br>

<div>
  <%= link_to "Show this mentor enrollment assignment", @mentor_enrollment_assignment %> |
  <%= link_to "Back to mentor enrollment assignments", mentor_enrollment_assignments_path %>
</div>

app/views/mentor_enrollment_assignments/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Mentor enrollment assignments" %>

<h1>Mentor enrollment assignments</h1>

<div id="mentor_enrollment_assignments">
  <% @mentor_enrollment_assignments.each do |mentor_enrollment_assignment| %>
    <%= render mentor_enrollment_assignment %>
    <p>
      <%= link_to "Show this mentor enrollment assignment", mentor_enrollment_assignment %>
    </p>
  <% end %>
</div>

<%= link_to "New mentor enrollment assignment", new_mentor_enrollment_assignment_path %>

app/views/mentor_enrollment_assignments/new.html.erb
<% content_for :title, "New mentor enrollment assignment" %>

<h1>New mentor enrollment assignment</h1>

<%= render "form", mentor_enrollment_assignment: @mentor_enrollment_assignment %>

<br>

<div>
  <%= link_to "Back to mentor enrollment assignments", mentor_enrollment_assignments_path %>
</div>

app/views/mentor_enrollment_assignments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mentor_enrollment_assignment %>

<div>
  <%= link_to "Edit this mentor enrollment assignment", edit_mentor_enrollment_assignment_path(@mentor_enrollment_assignment) %> |
  <%= link_to "Back to mentor enrollment assignments", mentor_enrollment_assignments_path %>

  <%= button_to "Destroy this mentor enrollment assignment", @mentor_enrollment_assignment, method: :delete %>
</div>