config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :mentors
  resources :enrollments
  resources :mentor_enrollment_assignments
  resources :lessons
  resources :courses
  resources :coding_classes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/mentor.rb
class Mentor < ApplicationRecord
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  before_action :set_mentor, only: %i[ show edit update destroy ]

  # GET /mentors or /mentors.json
  def index
    @mentors = Mentor.all
  end

  # GET /mentors/1 or /mentors/1.json
  def show
  end

  # GET /mentors/new
  def new
    @mentor = Mentor.new
  end

  # GET /mentors/1/edit
  def edit
  end

  # POST /mentors or /mentors.json
  def create
    @mentor = Mentor.new(mentor_params)

    respond_to do |format|
      if @mentor.save
        format.html { redirect_to @mentor, notice: "Mentor was successfully created." }
        format.json { render :show, status: :created, location: @mentor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mentors/1 or /mentors/1.json
  def update
    respond_to do |format|
      if @mentor.update(mentor_params)
        format.html { redirect_to @mentor, notice: "Mentor was successfully updated." }
        format.json { render :show, status: :ok, location: @mentor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentors/1 or /mentors/1.json
  def destroy
    @mentor.destroy!

    respond_to do |format|
      format.html { redirect_to mentors_path, status: :see_other, notice: "Mentor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mentor
      @mentor = Mentor.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def mentor_params
      params.expect(mentor: [ :first_name, :last_name, :email, :max_concurrent_students ])
    end
end

app/views/mentors/_form.html.erb
<%= form_with(model: mentor) do |form| %>
  <% if mentor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mentor.errors.count, "error") %> prohibited this mentor from being saved:</h2>

      <ul>
        <% mentor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :max_concurrent_students, style: "display: block" %>
    <%= form.number_field :max_concurrent_students %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mentors/_mentor.html.erb
<div id="<%= dom_id mentor %>">
  <p>
    <strong>First name:</strong>
    <%= mentor.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= mentor.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= mentor.email %>
  </p>

  <p>
    <strong>Max concurrent students:</strong>
    <%= mentor.max_concurrent_students %>
  </p>

</div>

app/views/mentors/edit.html.erb
<% content_for :title, "Editing mentor" %>

<h1>Editing mentor</h1>

<%= render "form", mentor: @mentor %>

<br>

<div>
  <%= link_to "Show this mentor", @mentor %> |
  <%= link_to "Back to mentors", mentors_path %>
</div>

app/views/mentors/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Mentors" %>

<h1>Mentors</h1>

<div id="mentors">
  <% @mentors.each do |mentor| %>
    <%= render mentor %>
    <p>
      <%= link_to "Show this mentor", mentor %>
    </p>
  <% end %>
</div>

<%= link_to "New mentor", new_mentor_path %>

app/views/mentors/new.html.erb
<% content_for :title, "New mentor" %>

<h1>New mentor</h1>

<%= render "form", mentor: @mentor %>

<br>

<div>
  <%= link_to "Back to mentors", mentors_path %>
</div>

app/views/mentors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mentor %>

<div>
  <%= link_to "Edit this mentor", edit_mentor_path(@mentor) %> |
  <%= link_to "Back to mentors", mentors_path %>

  <%= button_to "Destroy this mentor", @mentor, method: :delete %>
</div>